services:
  - type: web
    name: asr-parking-lot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_render_db.py && gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true